import { createContext, useContext } from 'react';
import { CheckSquare, Square } from 'lucide-react';
import { stampOf, inlineText } from './manualFormat';

/**
 * Renders the HR Suite Manual's block tree (src/components/hr/manual/
 * manualContent.js, generated by scripts/build-hr-manual.mjs) with React —
 * no HTML is ever injected. Covers what the manual uses: headings,
 * paragraphs, bold / italic / code, links (in-manual tab links are "#slug"),
 * bullet / numbered / checkbox lists with nesting and pictures inside items,
 * tables, figures with captions, diagrams and quotes.
 *
 * A checkbox list that is part of the shared checklist (list.checklist) shows
 * the clinic's live ticks — `checklist.byKey` — and ticks through
 * `checklist.onToggle` when the reader may.
 */

export const Inline = ({ nodes, onLink }) => (nodes || []).map((n, i) => {
  switch (n.t) {
    case 'text': return n.v;
    case 'b': return <strong key={i} className="font-semibold text-gray-900"><Inline nodes={n.c} onLink={onLink} /></strong>;
    case 'i': return <em key={i}><Inline nodes={n.c} onLink={onLink} /></em>;
    case 'code': return <code key={i} className="rounded bg-gray-100 px-1 py-0.5 text-[0.85em] font-mono">{n.v}</code>;
    case 'link':
      if (n.href.startsWith('#')) {
        return (
          <a key={i} href={n.href} className="text-primary underline decoration-primary/30 underline-offset-2 hover:decoration-primary"
            onClick={(e) => { e.preventDefault(); onLink?.(n.href.slice(1)); }}>
            <Inline nodes={n.c} onLink={onLink} />
          </a>
        );
      }
      return <a key={i} href={n.href} target="_blank" rel="noopener noreferrer" className="text-primary underline"><Inline nodes={n.c} onLink={onLink} /></a>;
    default: return null;
  }
});

const HEADING = {
  2: 'text-lg font-bold text-gray-900 mt-8 mb-3 pb-1 border-b border-gray-200',
  3: 'text-base font-semibold text-gray-900 mt-6 mb-2',
  4: 'text-sm font-semibold text-gray-800 mt-4 mb-2',
};

/** True inside the print copy of a tab: pictures load at once, not lazily. */
export const ManualPrintContext = createContext(false);

const Figure = ({ block, onImage }) => {
  const printing = useContext(ManualPrintContext);
  const caption = block.caption?.length ? <Inline nodes={block.caption} /> : null;
  const isDiagram = block.t === 'diagram';
  return (
    <figure className="hr-manual-figure my-4">
      <button type="button" onClick={() => onImage?.(block)} title="Click to enlarge"
        className={`block w-full overflow-hidden rounded-lg border border-gray-200 bg-white text-left cursor-zoom-in hover:border-primary/50 focus:outline-none focus:ring-2 focus:ring-primary/40 ${isDiagram ? 'p-2' : ''}`}>
        <img src={block.src} alt={block.alt} width={block.w} height={block.h} loading={printing ? 'eager' : 'lazy'} decoding="async"
          className="block h-auto w-full max-w-full" />
      </button>
      {(caption || isDiagram) && (
        <figcaption className="mt-1.5 text-xs italic text-gray-500">{caption || block.alt}</figcaption>
      )}
    </figure>
  );
};

const ChecklistItem = ({ item, checklist, onLink }) => {
  const state = checklist?.byKey?.[item.key];
  const done = !!state?.done;
  const Box = done ? CheckSquare : Square;
  const canTick = !!checklist?.onToggle;
  const [first, ...rest] = item.c;
  return (
    <li className="flex gap-2 py-0.5">
      <button type="button" disabled={!canTick || checklist?.busyKey === item.key}
        onClick={() => checklist.onToggle(item.key, !done)}
        aria-label={`${done ? 'Untick' : 'Tick'}: ${first?.t === 'p' ? inlineText(first.c) : item.key}`}
        aria-pressed={done}
        className={`mt-0.5 flex-none self-start rounded ${canTick ? 'hover:text-primary' : 'cursor-default'} ${done ? 'text-green-600' : 'text-gray-400'}`}>
        <Box className="h-4 w-4" />
      </button>
      <div className="min-w-0">
        <div className={done ? 'text-gray-500' : ''}>{first?.t === 'p' ? <Inline nodes={first.c} onLink={onLink} /> : null}</div>
        {done && state?.doneBy && (
          <div className="text-[11px] text-gray-500">Ticked by {state.doneBy} · {stampOf(state.doneAt)}</div>
        )}
        {rest.length > 0 && <Blocks blocks={rest} onLink={onLink} checklist={checklist} />}
      </div>
    </li>
  );
};

const List = ({ block, onLink, onImage, checklist }) => {
  if (block.checklist) {
    return <ul className="my-3 space-y-1 text-sm leading-relaxed text-gray-700">{block.items.map((it) => <ChecklistItem key={it.key} item={it} checklist={checklist} onLink={onLink} />)}</ul>;
  }
  const Tag = block.ordered ? 'ol' : 'ul';
  return (
    <Tag start={block.ordered && block.start !== 1 ? block.start : undefined}
      className={`my-3 space-y-1.5 pl-6 text-sm leading-relaxed text-gray-700 ${block.ordered ? 'list-decimal' : 'list-disc'} marker:text-gray-400`}>
      {block.items.map((it, i) => (
        <li key={i} className="pl-1">
          {it.check !== null && it.check !== undefined && (it.check ? <CheckSquare className="mr-1 inline h-4 w-4 text-green-600" /> : <Square className="mr-1 inline h-4 w-4 text-gray-400" />)}
          {it.c.map((b, j) => (b.t === 'p' && j === 0
            ? <span key={j}><Inline nodes={b.c} onLink={onLink} /></span>
            : <Block key={j} block={b} onLink={onLink} onImage={onImage} checklist={checklist} />))}
        </li>
      ))}
    </Tag>
  );
};

const Table = ({ block, onLink }) => (
  <div className="hr-manual-table my-4 overflow-x-auto rounded-lg border border-gray-200">
    <table className="min-w-full text-left text-sm">
      <thead className="bg-gray-50">
        <tr>{block.head.map((c, i) => <th key={i} className="px-3 py-2 text-[11px] font-semibold uppercase tracking-wide text-gray-500 align-bottom"><Inline nodes={c} onLink={onLink} /></th>)}</tr>
      </thead>
      <tbody className="divide-y divide-gray-100">
        {block.rows.map((r, i) => (
          <tr key={i} className="align-top">
            {r.map((c, j) => <td key={j} className={`px-3 py-2 text-gray-700 ${j === 0 ? 'font-medium text-gray-900' : ''}`}><Inline nodes={c} onLink={onLink} /></td>)}
          </tr>
        ))}
      </tbody>
    </table>
  </div>
);

export const Block = ({ block, onLink, onImage, checklist }) => {
  switch (block.t) {
    case 'h': {
      const Tag = `h${Math.min(Math.max(block.level, 2), 4)}`;
      return <Tag id={block.id} className={`scroll-mt-4 ${HEADING[block.level] || HEADING[4]}`}><Inline nodes={block.c} onLink={onLink} /></Tag>;
    }
    case 'p': return <p className="my-3 text-sm leading-relaxed text-gray-700"><Inline nodes={block.c} onLink={onLink} /></p>;
    case 'list': return <List block={block} onLink={onLink} onImage={onImage} checklist={checklist} />;
    case 'table': return <Table block={block} onLink={onLink} />;
    case 'quote': return <blockquote className="my-4 border-l-4 border-primary/40 bg-blue-50/50 px-4 py-2"><Blocks blocks={block.c} onLink={onLink} onImage={onImage} checklist={checklist} /></blockquote>;
    case 'img': case 'diagram': return block.src ? <Figure block={block} onImage={onImage} /> : null;
    default: return null;
  }
};

export const Blocks = ({ blocks, onLink, onImage, checklist, idPrefix }) => blocks.map((b, i) => (
  idPrefix
    ? <div key={i} id={`${idPrefix}-${i}`} className="hr-manual-block scroll-mt-4 rounded-md"><Block block={b} onLink={onLink} onImage={onImage} checklist={checklist} /></div>
    : <Block key={i} block={b} onLink={onLink} onImage={onImage} checklist={checklist} />
));
